services:
  - type: web
    name: b2b-backend
    runtime: python
    plan: free
    rootDir: b2b-backend
    buildCommand: pip install --upgrade pip && pip install --only-binary=:all: -r requirements.txt && alembic upgrade head
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIP_NO_BUILD_ISOLATION
        value: false
      - key: PIP_PREFER_BINARY
        value: 1
      - key: PIP_ONLY_BINARY
        value: :all:
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: DATABASE_URL
        fromDatabase:
          name: b2b-database
          property: connectionString
    healthCheckPath: /
    autoDeploy: false

databases:
  - name: b2b-database
    plan: free
    databaseName: b2b_marketplace
    user: b2b_user
