"""Add Master Admin system tables

Revision ID: a69d2d6ed100
Revises: 
Create Date: 2026-02-25 15:29:03.754675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69d2d6ed100'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('categories', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('categories', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'categories', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'categories', 'users', ['deleted_by'], ['id'])
    op.add_column('subcategories', sa.Column('icon', sa.String(length=255), nullable=True))
    op.add_column('subcategories', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('subcategories', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('subcategories', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('subcategories', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('subcategories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'subcategories', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'subcategories', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'subcategories', 'users', ['updated_by'], ['id'])
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login_at')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.drop_column('subcategories', 'deleted_at')
    op.drop_column('subcategories', 'deleted_by')
    op.drop_column('subcategories', 'updated_by')
    op.drop_column('subcategories', 'created_by')
    op.drop_column('subcategories', 'display_order')
    op.drop_column('subcategories', 'icon')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'deleted_at')
    op.drop_column('categories', 'deleted_by')
    op.drop_column('categories', 'updated_by')
    op.drop_column('categories', 'created_by')
    op.drop_column('categories', 'display_order')
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
